fields:
	hero_image:
		type: file
		destination: assets/img/
		display: Hero Image
		allowed: [jpeg, jpg, png]
	individual_subheader:
		type: text
		display: Individuals & Families Subheader
	individual_description:
		type: redactor
		display: Individuals & Families Description
	individual_services:
		type: suggest
		create: new
		display: Individual Services
		options:
			- Detailed valuation
			- Marketing strategy development
			- Marketing plan execution
			- Property prepping and staging
			- Day-to-day fielding of leads
			- Open houses & tours
			- Tenant issues
			- Offer evaluation & negotiation
			- Closing support
			- Annual asset value analysis
			- Management of real estate assets
			- Communicate with institutional boards
			- Sale or re-location of institutional real estate assets
			- Purchase of institution property
			- Advice and assitance on legal and accounting help
			- Goal-setting
			- Property search
			- Offer negotiation
			- Transaction support
	individual_quote:
		type: grid
		display: Individuals Quote(s)
		fields:
			main:
				type: textarea
				display: Main Quote Line
				height: 100
				width: 35%
			logo:
				type: file
				display: Image Logo
				destination: assets/img/services
			person:
				type: text
				display: Person's Name
				width: 20%
			description:
				type: textarea
				display: Quoted Person's Description
				width: 25%
				height: 100
	trust_subheader:
		type: text
		display: Trusts & Estates Subheader
	trust_description:
		type: redactor
		display: Trusts & Estates Description
	trust_services:
		type: suggest
		create: new
		display: Individual Services
		options:
			- Detailed valuation
			- Marketing strategy development
			- Marketing plan execution
			- Property prepping and staging
			- Day-to-day fielding of leads
			- Open houses & tours
			- Tenant issues
			- Offer evaluation & negotiation
			- Closing support
			- Annual asset value analysis
			- Management of real estate assets
			- Communicate with institutional boards
			- Sale or re-location of institutional real estate assets
			- Purchase of institution property
			- Advice and assitance on legal and accounting help
			- Goal-setting
			- Property search
			- Offer negotiation
			- Transaction support
	trust_quote:
		type: grid
		display: Trusts Quote(s)
		fields:
			main:
				type: textarea
				display: Main Quote Line
				height: 100
				width: 35%
			logo:
				type: file
				display: Image Logo
				destination: assets/img/services
			person:
				type: text
				display: Person's Name
				width: 20%
			description:
				type: textarea
				display: Quoted Person's Description
				width: 25%
				height: 100
	institution_subheader:
		type: text
		display: Institutions Subheader
	institution_description:
		type: redactor
		display: Institutions Description
	institution_services:
		type: suggest
		create: new
		display: Individual Services
		options:
			- Detailed valuation
			- Marketing strategy development
			- Marketing plan execution
			- Property prepping and staging
			- Day-to-day fielding of leads
			- Open houses & tours
			- Tenant issues
			- Offer evaluation & negotiation
			- Closing support
			- Annual asset value analysis
			- Management of real estate assets
			- Communicate with institutional boards
			- Sale or re-location of institutional real estate assets
			- Purchase of institution property
			- Advice and assitance on legal and accounting help
			- Goal-setting
			- Property search
			- Offer negotiation
			- Transaction support
	institution_quote:
		type: grid
		display: Institutions Quote(s)
		fields:
			main:
				type: textarea
				display: Main Quote Line
				height: 100
				width: 35%
			logo:
				type: file
				display: Image Logo
				destination: assets/img/services
			person:
				type: text
				display: Person's Name
				width: 20%
			description:
				type: textarea
				display: Quoted Person's Description
				width: 25%
				height: 100
	buyers_subheader:
		type: text
		display: Buyers Subheader
	buyers_description:
		type: redactor
		display: Buyers Description
	buyers_services:
		type: suggest
		create: new
		display: Individual Services
		options:
			- Detailed valuation
			- Marketing strategy development
			- Marketing plan execution
			- Property prepping and staging
			- Day-to-day fielding of leads
			- Open houses & tours
			- Tenant issues
			- Offer evaluation & negotiation
			- Closing support
			- Annual asset value analysis
			- Management of real estate assets
			- Communicate with institutional boards
			- Sale or re-location of institutional real estate assets
			- Purchase of institution property
			- Advice and assitance on legal and accounting help
			- Goal-setting
			- Property search
			- Offer negotiation
			- Transaction support
	buyers_quote:
		type: grid
		display: Buyers Quote(s)
		fields:
			main:
				type: textarea
				display: Main Quote Line
				height: 100
				width: 35%
			logo:
				type: file
				display: Image Logo
				destination: assets/img/services
			person:
				type: text
				display: Person's Name
				width: 20%
			description:
				type: textarea
				display: Quoted Person's Description
				width: 25%
				height: 100
	content:
		hide: true

