fields:
	hero_image:
		type: file
		destination: assets/img/
		display: Hero Image
		allowed: [jpeg, jpg, png]
	individual_subheader:
		type: text
		display: Individuals & Families Subheader
	individual_description:
		type: redactor
		display: Individuals & Families Description
	individual_services:
		type: suggest
		create: new
		display: Individual Services
		options:
			- Detailed valuation
			- Marketing strategy development
			- Marketing plan execution
			- Property prepping and staging
			- Day-to-day fielding of leads
			- Open houses & tours
			- Tenant issues
			- Offer evaluation & negotiation
			- Closing support
	individual_quote:
		type: grid
		display: Individuals Quote(s)
		fields:
			main:
				type: text
				display: Main Quote Line
			person:
				type: text
				display: Person's Name
				width: 25%
	trust_subheader:
		type: text
		display: Trusts & Estates Subheader
	trust_description:
		type: redactor
		display: Trusts & Estates Description
	trust_services:
		type: suggest
		create: new
		display: Individual Services
		options:
			- Detailed valuation
			- Marketing strategy development
			- Marketing plan execution
			- Property prepping and staging
			- Day-to-day fielding of leads
			- Open houses & tours
			- Tenant issues
			- Offer evaluation & negotiation
			- Closing support
	trust_quote:
		type: grid
		display: Trusts Quote(s)
		fields:
			main:
				type: text
				display: Main Quote Line
			person:
				type: text
				display: Person's Name
				width: 15%
			description:
				type: text
				display: Description of Quote
	content:
		hide: true

